include $(MOD_CFG)
# DIR_SRC := src
# DIR_INC := inc 
# ifneq ("$(DIR_COMMON_INC)","")
# DIR_INC += $(DIR_COMMON_INC)
# endif

# TYPE_INC := .h
# TYPE_SRC := .c
# TYPE_OBJ := .o 
# TYPE_DEP := .dep 

include $(CMD_CFG)
include $(MOD_RULE)
